<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 1 / NOTE 1*

---

# 📝 Assignment

# **🌱 기본 과제**

## **Part 1. EDA**

### **1-1. 데이터셋 불러오기**

우리는 이 과제를 통해 아래의 url에 존재하는 Travel.xlsx를 Pandads의 데이터프레임으로 가져와 데이터에서 의미를 도출하고자 합니다. 
- https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/stocks/Travel.xlsx

유의해야 할 점은 데이터를 불러올때, 그 파일의 형태와 구조에 따라 올바르게 불러와야 한다는 점입니다. <br> 

우선, 이 파일은 `.csv` 형태가 아닌 `.xlsx` 파일 형태입니다. 그러므로 Pandas의 `read_csv` 메서드가 아닌 `read_excel` 메서드를 활용하여 데이터를 가져와야 합니다. 또한, 이 파일은 2개의 시트로 구성되어 있으며 시트명은 각각 `008770` , `035250` 입니다. <br>

아래의 코드 Tip과 첨부된 링크를 활용하여 각 시트의 데이터가 다음 이미지와 같은 데이터프레임 형식을 갖도록 만드세요.

<img src='https://i.imgur.com/G1rLOnh.png'>

- `008770` 시트의 데이터는 **df1**으로, `035250` 시트의 데이터는 **df2**로 저장합니다.

<br>

> **💡 Tip**
1. df = pd[.read_excel](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)(url, sheet_name = 0)
2. df = df[.T](https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.DataFrame.T.html)
3. df_columns = df1[.loc](https://stackoverflow.com/questions/31593201/how-are-iloc-and-loc-different)[0]
4. df[.columns](https://stackoverflow.com/questions/31328861/python-pandas-replacing-header-with-top-row) = df_columns
5. df = df[1:]

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# 파일 url
url = 'https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/stocks/Travel.xlsx'

# 데이터프레임으로 불러오기
df1 = pd.read_excel(url, sheet_name= 0)
df2 = pd.read_excel(url, sheet_name= 1)

In [ ]:
df1.head(3)

,주요재무정보,2019/09\n(IFRS연결),2019/12\n(IFRS연결),2020/03\n(IFRS연결),2020/06\n(IFRS연결),2020/09\n(IFRS연결),2020/12(E)\n(IFRS연결),2021/03(E)\n(IFRS연결),2021/06(E)\n(IFRS연결)
0,매출액,14753.0,15440.0,9437.0,5230.0,8795.0,9980.0,9761.0,9820.0
1,영업이익,574.0,776.0,-668.0,-634.0,-198.0,50.0,144.0,265.0
2,영업이익(발표기준),574.0,776.0,-668.0,-634.0,-198.0,NaN,NaN,NaN

In [ ]:
df2.head(3)

,주요재무정보,2019/09\n(IFRS연결),2019/12\n(IFRS연결),2020/03\n(IFRS연결),2020/06\n(IFRS연결),2020/09\n(IFRS연결),2020/12(E)\n(IFRS연결),2021/03(E)\n(IFRS연결),2021/06(E)\n(IFRS연결)
0,매출액,4055.0,3728.0,2360.0,346.0,766.0,1581.0,1473.0,1746.0
1,영업이익,1392.0,641.0,-1868.0,-1038.0,-649.0,-434.0,-187.0,-65.0
2,영업이익(발표기준),1392.0,641.0,-1868.0,-1038.0,-649.0,NaN,NaN,NaN

In [ ]:
# 한 줄씩 실행해 보며 데이터프레임이 어떻게 바뀌어 가는지 살펴보세요. 
# column에 특성이 나타나도록 행과 열을 바꿉니다. 
df1 = df1.T
df2 = df2.T

In [ ]:
# 0번째 row에 있는 컬럼명을 df_columns 변수에 저장해 둡니다. 
df_columns = df1.iloc[0]

# 헤더에 index가 있으므로 이를 컬럼명으로 바꿔줍니다. 
df1.columns = df_columns
df2.columns = df_columns

In [ ]:
# 헤더에 컬럼명이 잘 들어왔으므로 0번째 row는 더이상 필요하지 않습니다. 
# 슬라이싱을 활용하여 0번째 row는 제외하고 나머지 row만 추출합니다. 
df1 = df1[1:]
df2 = df2[1:]

In [ ]:
df1.head(3)

주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,ROA(%),부채비율,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%)
2019/09\n(IFRS연결),14753.0,574.0,574.0,376.0,274.0,277.0,-3.0,37747.0,28854.0,8893.0,...,3.62,324.45,395.1,692.0,31.19,23484.0,3.67,0.0,NaN,0.0
2019/12\n(IFRS연결),15440.0,776.0,776.0,538.0,380.0,380.0,0.0,35273.0,26077.0,9195.0,...,5.81,283.59,411.78,950.0,21.4,24282.0,3.74,350.0,NaN,34.94
2020/03\n(IFRS연결),9437.0,-668.0,-668.0,-925.0,-736.0,-736.0,0.0,33188.0,24813.0,8375.0,...,1.25,296.28,368.36,-1839.0,63.76,22114.0,3.19,NaN,NaN,0.0

In [ ]:
df2.head(3)

주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,ROA(%),부채비율,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%)
2019/09\n(IFRS연결),4055.0,1392.0,1392.0,1554.0,1286.0,1286.0,0.0,41698.0,4781.0,36917.0,...,7.2,12.95,3513.86,601.0,21.0,18209.0,1.62,0.0,NaN,0.0
2019/12\n(IFRS연결),3728.0,641.0,641.0,769.0,526.0,526.0,0.0,44381.0,7204.0,37178.0,...,7.72,19.38,3538.24,246.0,18.92,18337.0,1.61,900.0,NaN,346.75
2020/03\n(IFRS연결),2360.0,-1868.0,-1868.0,-2204.0,-1561.0,-1561.0,0.0,43702.0,9945.0,33757.0,...,1.75,29.46,3218.48,-730.0,55.53,16650.0,1.19,NaN,NaN,NaN

##### **Q1. `df1`의 shape을 쓰세요.**

In [ ]:
df1.shape

(8, 32)

##### **Q2. `df2`의 shape을 쓰세요.**

In [ ]:
df2.shape

(8, 32)

### **1-2. 결측치 확인**

- df1과 df2의 결측치를 확인하세요.
  - 두 데이터 프레임의 결측치 확인 후, 
[.fillna()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html) 메서드를 활용하여 결측치를 0으로 대체하세요. <br>
- 결측치 대체 후에 제대로 코드가 작동 하였는지 확인하도록 합니다.

##### **Q3. `df1`의 -1번째 column의 결측치는 모두 몇 개인지 구하세요.**

In [ ]:
df1.iloc[:,-1].isnull().sum()

4

##### **Q4. `df2`의 -1번째 column의 결측치는 모두 몇 개인지 구하세요.**

In [ ]:
df2.iloc[:,-1].isnull().sum()

5

In [ ]:
# 결측치를 0으로 대체 
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [ ]:
# 결측치가 잘 대체되었는지 확인 
df1.isnull().sum()

주요재무정보
매출액           0
영업이익          0
영업이익(발표기준)    0
세전계속사업이익      0
당기순이익         0
당기순이익(지배)     0
당기순이익(비지배)    0
자산총계          0
부채총계          0
자본총계          0
자본총계(지배)      0
자본총계(비지배)     0
자본금           0
영업활동현금흐름      0
투자활동현금흐름      0
재무활동현금흐름      0
CAPEX         0
FCF           0
이자발생부채        0
영업이익률         0
순이익률          0
ROE(%)        0
ROA(%)        0
부채비율          0
자본유보율         0
EPS(원)        0
PER(배)        0
BPS(원)        0
PBR(배)        0
현금DPS(원)      0
현금배당수익률       0
현금배당성향(%)     0
dtype: int64

In [ ]:
df2.isnull().sum()

주요재무정보
매출액           0
영업이익          0
영업이익(발표기준)    0
세전계속사업이익      0
당기순이익         0
당기순이익(지배)     0
당기순이익(비지배)    0
자산총계          0
부채총계          0
자본총계          0
자본총계(지배)      0
자본총계(비지배)     0
자본금           0
영업활동현금흐름      0
투자활동현금흐름      0
재무활동현금흐름      0
CAPEX         0
FCF           0
이자발생부채        0
영업이익률         0
순이익률          0
ROE(%)        0
ROA(%)        0
부채비율          0
자본유보율         0
EPS(원)        0
PER(배)        0
BPS(원)        0
PBR(배)        0
현금DPS(원)      0
현금배당수익률       0
현금배당성향(%)     0
dtype: int64

### **1-3. GitHub Pull Request**

> 아래 **`🥇 도전과제`**를 풀 경우, 도전과제까지 모두 마친 후 이 문항을 마지막에 수행합니다. 

- 다음 링크를 통해 chrome에 **`open in colab`**을 설치합니다. <br>
  https://chrome.google.com/webstore/detail/open-in-colab/iogfkhleblhcpcekbiedikdehleodpjo
- colab에서 **`도구`** > **`설정`** > **`GitHub`** 으로 이동해 **`비공개 저장소 및 조직에 액세스`**에 체크합니다. <br>
  https://colab.research.google.com/
- 유어클래스의 **`[AIB] Archives`** > **`AI 부트캠프 DOCs`** > **`1. Colab 을 통한 Pull Request 과제제출`**을 참고하여 깃헙에 n111a를 PR합니다. <br>
  https://urclass.codestates.com/content/a18a5115-f614-49ab-810a-87f5024c3297?playlist=2461
- **`변경사항 설명 메세지`**에는 **`[n111a] 1차 제출`** 이라고 씁니다.

# **🥇 도전 과제**

## **Part 2. Missing Value**
**자산총계의 결측치를 처리하세요.** 

앞선 문제에서는 결측치를 단순히 0으로 처리하였으나, 결측치를 처리하는 방법은 그 외에도 여러가지가 있습니다. <br>
다양한 imputation 방법에 대해 알아보고, 그 중 mean imputation 방법을 사용하여 `자산총계`의 결측치를 처리해보세요.

In [ ]:
# 데이터를 새 변수에 저장 
df1_re = pd.read_excel(url, sheet_name= 0)
df2_re = pd.read_excel(url, sheet_name= 1)

In [ ]:
df1_re = df1_re.T
df2_re = df2_re.T

df1_re.columns = df_columns
df2_re.columns = df_columns

df1_re = df1_re[1:]
df2_re = df2_re[1:]

In [ ]:
# 자산총계 평균값 
df1['자산총계'].mean()

25539.75

In [ ]:
df2['자산총계'].mean()

30583.0

In [ ]:
# 자산총계 column의 결측치를 평균값으로 대체 
df1_re['자산총계'] = df1_re['자산총계'].fillna(df1['자산총계'].mean())
df1_re['자산총계']

2019/09\n(IFRS연결)       37747.00
2019/12\n(IFRS연결)       35273.00
2020/03\n(IFRS연결)       33188.00
2020/06\n(IFRS연결)       33039.00
2020/09\n(IFRS연결)       32683.00
2020/12(E)\n(IFRS연결)    32388.00
2021/03(E)\n(IFRS연결)    25539.75
2021/06(E)\n(IFRS연결)    25539.75
Name: 자산총계, dtype: float64

In [ ]:
df2_re['자산총계'] = df2_re['자산총계'].fillna(df2['자산총계'].mean())
df2_re['자산총계']

2019/09\n(IFRS연결)       41698.0
2019/12\n(IFRS연결)       44381.0
2020/03\n(IFRS연결)       43702.0
2020/06\n(IFRS연결)       39178.0
2020/09\n(IFRS연결)       37434.0
2020/12(E)\n(IFRS연결)    38271.0
2021/03(E)\n(IFRS연결)    30583.0
2021/06(E)\n(IFRS연결)    30583.0
Name: 자산총계, dtype: float64

## **Part 3. Feature Engineering**

##### **`부채 비율 2` 라는 새로운 피쳐를 생성하세요.**

> 부채 비율(%) = (부채총액 / 자본총액) x 100

위의 공식을 활용하여 `부채 비율 2` 라는 column을 생성합니다. 그리고, 생성한 column과 기존 `부채 비율` column의 값이 동일한지 확인해봅니다.

In [ ]:
df1['부채비율2'] = (df1['부채총계']/df1['자본총계'])*100
df1

주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,부채비율,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),부채비율2
2019/09\n(IFRS연결),14753.0,574.0,574.0,376.0,274.0,277.0,-3.0,37747.0,28854.0,8893.0,...,324.45,395.10,692.0,31.19,23484.0,3.67,0.0,0,0.00,324.457438
2019/12\n(IFRS연결),15440.0,776.0,776.0,538.0,380.0,380.0,0.0,35273.0,26077.0,9195.0,...,283.59,411.78,950.0,21.40,24282.0,3.74,350.0,0,34.94,283.599782
2020/03\n(IFRS연결),9437.0,-668.0,-668.0,-925.0,-736.0,-736.0,0.0,33188.0,24813.0,8375.0,...,296.28,368.36,-1839.0,63.76,22114.0,3.19,0.0,0,0.00,296.274627
2020/06\n(IFRS연결),5230.0,-634.0,-634.0,-819.0,-677.0,-678.0,1.0,33039.0,25364.0,7676.0,...,330.45,334.46,-1695.0,0.00,20265.0,3.50,0.0,0,0.00,330.432517
2020/09\n(IFRS연결),8795.0,-198.0,-198.0,-366.0,-285.0,-285.0,0.0,32683.0,25318.0,7365.0,...,343.77,320.21,-712.0,0.00,19444.0,3.91,0.0,0,0.00,343.761032
2020/12(E)\n(IFRS연결),9980.0,50.0,0.0,-109.0,-100.0,-100.0,0.0,32388.0,25171.0,7216.0,...,348.79,0.00,-251.0,0.00,19187.0,4.22,0.0,0,0.00,348.822062
2021/03(E)\n(IFRS연결),9761.0,144.0,0.0,14.0,71.0,53.0,0.0,0.0,0.0,0.0,...,0.00,0.00,133.0,0.00,0.0,0.00,0.0,0,0.00,NaN
2021/06(E)\n(IFRS연결),9820.0,265.0,0.0,172.0,214.0,123.0,0.0,0.0,0.0,0.0,...,0.00,0.00,308.0,0.00,0.0,0.00,0.0,0,0.00,NaN

In [ ]:
df2['부채비율2'] = (df2['부채총계']/df2['자본총계'])*100
df2

주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,부채비율,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),부채비율2
2019/09\n(IFRS연결),4055.0,1392.0,1392.0,1554.0,1286.0,1286.0,0.0,41698.0,4781.0,36917.0,...,12.95,3513.86,601.0,21.00,18209.0,1.62,0.0,0,0.00,12.950673
2019/12\n(IFRS연결),3728.0,641.0,641.0,769.0,526.0,526.0,0.0,44381.0,7204.0,37178.0,...,19.38,3538.24,246.0,18.92,18337.0,1.61,900.0,0,346.75,19.377051
2020/03\n(IFRS연결),2360.0,-1868.0,-1868.0,-2204.0,-1561.0,-1561.0,0.0,43702.0,9945.0,33757.0,...,29.46,3218.48,-730.0,55.53,16650.0,1.19,0.0,0,0.00,29.460556
2020/06\n(IFRS연결),346.0,-1038.0,-1038.0,-723.0,-456.0,-456.0,0.0,39178.0,5900.0,33277.0,...,17.73,3173.64,-213.0,0.00,16414.0,1.31,0.0,0,0.00,17.729964
2020/09\n(IFRS연결),766.0,-649.0,-649.0,-552.0,-409.0,-409.0,0.0,37434.0,4560.0,32875.0,...,13.87,3136.00,-191.0,0.00,16215.0,1.33,0.0,0,0.00,13.870722
2020/12(E)\n(IFRS연결),1581.0,-434.0,0.0,-331.0,-465.0,-314.0,0.0,38271.0,5998.0,32274.0,...,18.58,0.00,-147.0,0.00,15888.0,1.46,0.0,0,0.00,18.584619
2021/03(E)\n(IFRS연결),1473.0,-187.0,0.0,0.0,0.0,-33.0,0.0,0.0,0.0,0.0,...,0.00,0.00,-15.0,0.00,0.0,0.00,0.0,0,0.00,NaN
2021/06(E)\n(IFRS연결),1746.0,-65.0,0.0,0.0,0.0,135.0,0.0,0.0,0.0,0.0,...,0.00,0.00,63.0,0.00,0.0,0.00,0.0,0,0.00,NaN

##### **`종목` 이라는 새로운 피쳐를 생성하세요.**

**`.repeat()`**를 활용하여 새로운 `종목`이라는 새로운 column을 생성합니다.
  - `df1`의 `종목` column에는 `008770` 문자열이 담기도록 합니다.  
  - `df2`의 `종목` column에는 `035250` 문자열이 담기도록 합니다. 

각각의 데이터 프레임에 `종목`이라는 column을 만든 후, 최종적으로 두 데이터프레임 `df1`과 `df2`를 **`.append()`**를 활용하여 합쳐주도록 합니다.

In [ ]:
import numpy as np

df1_new = np.repeat('008770', len(df1))
df2_new = np.repeat('035250', len(df2))

In [ ]:
df1['종목'] = df1_new
df2['종목'] = df2_new

In [ ]:
# 데이터프레임 합치기
df = df1.append(df2)
df

주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),부채비율2,종목
2019/09\n(IFRS연결),14753.0,574.0,574.0,376.0,274.0,277.0,-3.0,37747.0,28854.0,8893.0,...,395.10,692.0,31.19,23484.0,3.67,0.0,0,0.00,324.457438,008770
2019/12\n(IFRS연결),15440.0,776.0,776.0,538.0,380.0,380.0,0.0,35273.0,26077.0,9195.0,...,411.78,950.0,21.40,24282.0,3.74,350.0,0,34.94,283.599782,008770
2020/03\n(IFRS연결),9437.0,-668.0,-668.0,-925.0,-736.0,-736.0,0.0,33188.0,24813.0,8375.0,...,368.36,-1839.0,63.76,22114.0,3.19,0.0,0,0.00,296.274627,008770
2020/06\n(IFRS연결),5230.0,-634.0,-634.0,-819.0,-677.0,-678.0,1.0,33039.0,25364.0,7676.0,...,334.46,-1695.0,0.00,20265.0,3.50,0.0,0,0.00,330.432517,008770
2020/09\n(IFRS연결),8795.0,-198.0,-198.0,-366.0,-285.0,-285.0,0.0,32683.0,25318.0,7365.0,...,320.21,-712.0,0.00,19444.0,3.91,0.0,0,0.00,343.761032,008770
2020/12(E)\n(IFRS연결),9980.0,50.0,0.0,-109.0,-100.0,-100.0,0.0,32388.0,25171.0,7216.0,...,0.00,-251.0,0.00,19187.0,4.22,0.0,0,0.00,348.822062,008770
2021/03(E)\n(IFRS연결),9761.0,144.0,0.0,14.0,71.0,53.0,0.0,0.0,0.0,0.0,...,0.00,133.0,0.00,0.0,0.00,0.0,0,0.00,NaN,008770
2021/06(E)\n(IFRS연결),9820.0,265.0,0.0,172.0,214.0,123.0,0.0,0.0,0.0,0.0,...,0.00,308.0,0.00,0.0,0.00,0.0,0,0.00,NaN,008770
2019/09\n(IFRS연결),4055.0,1392.0,1392.0,1554.0,1286.0,1286.0,0.0,41698.0,4781.0,36917.0,...,3513.86,601.0,21.00,18209.0,1.62,0.0,0,0.00,12.950673,035250
2019/12\n(IFRS연결),3728.0,641.0,641.0,769.0,526.0,526.0,0.0,44381.0,7204.0,37178.0,...,3538.24,246.0,18.92,18337.0,1.61,900.0,0,346.75,19.377051,035250
2020/03\n(IFRS연결),2360.0,-1868.0,-1868.0,-2204.0,-1561.0,-1561.0,0.0,43702.0,9945.0,33757.0,...,3218.48,-730.0,55.53,16650.0,1.19,0.0,0,0.00,29.460556,035250
2020/06\n(IFRS연결),346.0,-1038.0,-1038.0,-723.0,-456.0,-456.0,0.0,39178.0,5900.0,33277.0,...,3173.64,-213.0,0.00,16414.0,1.31,0.0,0,0.00,17.729964,035250
2020/09\n(IFRS연결),766.0,-649.0,-649.0,-552.0,-409.0,-409.0,0.0,37434.0,4560.0,32875.0,...,3136.00,-191.0,0.00,16215.0,1.33,0.0,0,0.00,13.870722,035250
2020/12(E)\n(IFRS연결),1581.0,-434.0,0.0,-331.0,-465.0,-314.0,0.0,38271.0,5998.0,32274.0,...,0.00,-147.0,0.00,15888.0,1.46,0.0,0,0.00,18.584619,035250
2021/03(E)\n(IFRS연결),1473.0,-187.0,0.0,0.0,0.0,-33.0,0.0,0.0,0.0,0.0,...,0.00,-15.0,0.00,0.0,0.00,0.0,0,0.00,NaN,035250
2021/06(E)\n(IFRS연결),1746.0,-65.0,0.0,0.0,0.0,135.0,0.0,0.0,0.0,0.0,...,0.00,63.0,0.00,0.0,0.00,0.0,0,0.00,NaN,035250